## Introspección

Cómo hacerse preguntas sobre Julia desde Julia.

    Es muy importante para aprender -- trabajar -- documentar

### Estructuras de Datos

In [13]:
a = 1
typeof(a)

Int64

In [25]:
sizeof(a)

8

In [27]:
aa = Int32(1)
sizeof(aa)

4

In [12]:
b = 1.
typeof(b)

Float64

In [22]:
sizeof(b)

8

In [23]:
c = 1 + im*5
typeof(c)


16

In [24]:
sizeof(c)

16

In [17]:
typeof(1//1)

Rational{Int64}

In [28]:
sizeof(1//1)

16

In [21]:
A = [1. 2. 6.]
#typeof(A)

24

In [ ]:
sizeof(A)

In [30]:
B = [1.; 2. ; 6.]
typeof(B)

Vector{Float64} (alias for Array{Float64, 1})

In [1]:
typeof(true)

Bool

In [2]:
typeof(1 < 2)

Bool

In [32]:
typeof(1:0.1:4)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}

In [33]:
typeof(sin)

typeof(sin) (singleton type of function sin, subtype of Function)

### Funciones

En el REPL si escriben `? <ENTER>` verán un nuevo pront:

`|help>` 

```|help> sin
search: sin sinh sind sinc sinpi sincos sincosd sincospi asin using isinf asinh asind isinteger isinteractive thisind sign signed Signed signbit significand

  sin(x)

  Compute sine of x, where x is in radians.

  See also [sind], [sinpi], [sincos], [cis].

  ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

  sin(A::AbstractMatrix)

  Compute the matrix sine of a square matrix A.

  If A is symmetric or Hermitian, its eigendecomposition (eigen) is used to compute the sine. Otherwise, the sine is determined by calling exp.

  Examples
  ≡≡≡≡≡≡≡≡≡≡

  julia> sin(fill(1.0, (2,2)))
  2×2 Matrix{Float64}:
   0.454649  0.454649
   0.454649  0.454649
```

En jupyter simplemente escriben 

In [3]:
?sin

search: sin sinh sind sinc sinpi sincos sincosd sincospi asin using isinf asinh



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

See also [`sind`], [`sinpi`], [`sincos`], [`cis`].

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Matrix{Float64}:
 0.454649  0.454649
 0.454649  0.454649
```


Tambien se pueden ver todos los métodos asociados a una función en particular:

In [4]:
methods(sin)

# 13 methods for generic function "sin":
[1] sin(x::T) where T<:Union{Float32, Float64} in Base.Math at special/trig.jl:29
[2] sin(A::LinearAlgebra.Hermitian{var"#s858", S} where {var"#s858"<:Complex, S<:(AbstractMatrix{<:var"#s858"})}) in LinearAlgebra at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/symmetric.jl:761
[3] sin(A::Union{LinearAlgebra.Hermitian{var"#s859", S}, LinearAlgebra.Symmetric{var"#s859", S}} where {var"#s859"<:Real, S}) in LinearAlgebra at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/symmetric.jl:757
[4] sin(D::LinearAlgebra.Diagonal) in LinearAlgebra at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/diagonal.jl:592
[5] sin(A::AbstractMatrix{<:Real}) in LinearAlgebra at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:931
[6] sin(A::AbstractMatrix{<:Complex}) in LinearAlgebra at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/dense.jl:938
[7] sin(J::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/LinearAlgebra/src/uniformscaling.jl:174
[8] sin(a::Float16) in Base.Math at math.jl:1201
[9] sin(a::ComplexF16) in Base.Math at math.jl:1202
[10] sin(z::Complex{T}) where T in Base at complex.jl:852
[11] sin(::Missing) in Base.Math at math.jl:1223
[12] sin(x::BigFloat) in Base.MPFR at mpfr.jl:742
[13] sin(x::Real) in Base.Math at math.jl:1218

### Un ejemplo de documentación: ###

In [5]:
"""Esta función duplica el argumento
admite tanto números como strings

### Examples
julia> eldoble(2.)

julia> 4.

julia> eldoble("dos")

julia> "dosdos"
"""
function eldoble(x)
    return 2*x
end
function eldoble(s::String)
    return s * s
end

eldoble(2)

4

In [6]:
eldoble("dos")

"dosdos"

In [7]:
?eldoble

search: eldoble



Esta función duplica el argumento admite tanto números como strings

### Examples

julia> eldoble(2.) julia> 4. julia> eldoble("dos") julia> "dosdos"


In [8]:
methods(eldoble)

# 2 methods for generic function "eldoble":
[1] eldoble(s::String) in Main at In[5]:13
[2] eldoble(x) in Main at In[5]:10

In [36]:
@which eldoble("dos")

eldoble(s::String) in Main at In[5]:13

In [9]:
eldoble([1;2])

2-element Vector{Int64}:
 2
 4

In [10]:
eldoble.(("uno", "dos"))

("unouno", "dosdos")

In [18]:
module mis_funciones
"""
funcion que triplica el valor del argumento
"""
function eltriple(x)
    return 3*x
end
function uncuarto(x)
    return x/4
end
    
end

Main.mis_funciones

In [19]:
using Main.mis_funciones

In [20]:
names(Main.mis_funciones)

1-element Vector{Symbol}:
 :mis_funciones

In [21]:
show(apropos(Main.mis_funciones))

Main.mis_funciones
nothing

In [24]:
using LinearAlgebra

In [25]:
?LinearAlgebra

search: LinearAlgebra



Linear algebra module. Provides array arithmetic, matrix factorizations and other linear algebra related functionality.


In [ ]:
apropos(LinearAlgebra)

Base.identity
Base.parent
Base.isapprox
Base.one
Base.Threads.@threads
Base.Threads.nthreads
Base.permutedims
LinearAlgebra.MulAddMul
LinearAlgebra.peakflops
LinearAlgebra.isbanded
LinearAlgebra.stride1
LinearAlgebra.promote_leaf_eltypes
LinearAlgebra.Givens
LinearAlgebra.LQ
LinearAlgebra.hessenberg
LinearAlgebra.issuccess
LinearAlgebra.lmul!
LinearAlgebra.rmul!
LinearAlgebra.det_bareiss!
LinearAlgebra.givens
LinearAlgebra._modify!
LinearAlgebra.det_bareiss
LinearAlgebra.lq
LinearAlgebra.qr
LinearAlgebra.Factorization
LinearAlgebra.checksquare
LinearAlgebra.qr!
InteractiveUtils.peakflops


In [15]:
names(LinearAlgebra)

129-element Vector{Symbol}:
 :/
 :Adjoint
 :BLAS
 :Bidiagonal
 :BunchKaufman
 :Cholesky
 :CholeskyPivoted
 :ColumnNorm
 :Diagonal
 :Eigen
 :Factorization
 :GeneralizedEigen
 :GeneralizedSVD
 ⋮
 :svdvals
 :svdvals!
 :sylvester
 :tr
 :transpose
 :transpose!
 :tril
 :tril!
 :triu
 :triu!
 :×
 :⋅

In [17]:
?mis_funciones

search: mis_funciones



No docstring or readme file found for module `Main.mis_funciones`.

Module does not export any names.


## Detalles del Código

El texto que nosotros escribimos es transformado sucesivamente hasta llegar al código que utiliza la máquina específica.

- `@code_lowered`: Código sin los aditivos que ayudan a la interfase humana.

- `@code_typed`: Los tipos de variables que se iran usando y sus conversiones.

- `@code_llvm`: Codigo compilado genérico.

- `@code_native`: Código asembler para la arquitectura de la computadora.

In [43]:
#x = 5
x = 3.0 + 1.0im
#x = [1 2 3]

3.0 + 1.0im

In [48]:
@code_lowered 1 * x

CodeInfo(
1 ─ %1 = Base.real(z)
│   %2 = x * %1
│   %3 = Base.imag(z)
│   %4 = x * %3
│   %5 = Base.Complex(%2, %4)
└──      return %5
)

In [49]:
@code_typed 1 * x

CodeInfo(
1 ─ %1 = Base.getfield(z, :re)::Float64
│   %2 = Base.sitofp(Float64, x)::Float64
│   %3 = Base.mul_float(%2, %1)::Float64
│   %4 = Base.getfield(z, :im)::Float64
│   %5 = Base.sitofp(Float64, x)::Float64
│   %6 = Base.mul_float(%5, %4)::Float64
│   %7 = %new(ComplexF64, %3, %6)::ComplexF64
└──      return %7
) => ComplexF64

In [47]:
@code_llvm 1 * x

;  @ complex.jl:333 within `*`
define void @"julia_*_2780"([2 x double]* noalias nocapture sret([2 x double]) %0, i64 signext %1, [2 x double]* nocapture nonnull readonly align 8 dereferenceable(16) %2) #0 {
top:
;  @ complex.jl:333 within `*` @ promotion.jl:380
; ┌ @ promotion.jl:350 within `promote`
; │┌ @ promotion.jl:327 within `_promote`
; ││┌ @ number.jl:7 within `convert`
; │││┌ @ float.jl:146 within `Float64`
      %3 = sitofp i64 %1 to double
; └└└└
;  @ complex.jl:333 within `*` @ promotion.jl:380 @ float.jl:405
  %4 = bitcast [2 x double]* %2 to <2 x double>*
  %5 = load <2 x double>, <2 x double>* %4, align 8
  %6 = insertelement <2 x double> poison, double %3, i32 0
  %7 = shufflevector <2 x double> %6, <2 x double> undef, <2 x i32> zeroinitializer
  %8 = fmul <2 x double> %5, %7
;  @ complex.jl:333 within `*`
  %9 = bitcast [2 x double]* %0 to <2 x double>*
  store <2 x double> %8, <2 x double>* %9, align 8
  ret void
}


In [50]:
@code_native 1 * x

	.section	__TEXT,__text,regular,pure_instructions
; ┌ @ complex.jl:333 within `*` @ promotion.jl:380
; │┌ @ promotion.jl:350 within `promote`
; ││┌ @ promotion.jl:327 within `_promote`
; │││┌ @ number.jl:7 within `convert`
; ││││┌ @ float.jl:146 within `Float64`
	vcvtsi2sd	%rsi, %xmm0, %xmm0
	movq	%rdi, %rax
; │└└└└
; │ @ complex.jl:333 within `*` @ promotion.jl:380 @ float.jl:405
	vmovddup	%xmm0, %xmm0                    ## xmm0 = xmm0[0,0]
	vmulpd	(%rdx), %xmm0, %xmm0
; │ @ complex.jl:333 within `*`
	vmovupd	%xmm0, (%rdi)
	retq
	nopw	%cs:(%rax,%rax)
; └
